In [2]:
'''
requires_grad=True，设置为true以后，就可以在这上面追踪梯度了。缺失情况下默认为False。
x.requires_grad_(True)#将属性设置为True
.detach()#分离梯度
with torch.no_grad()#分离梯度（将下面的代码块分离出来）
x.grad:查看梯度
x.grad_fn：创建这个tensor的函数
.outbackward()#之后，就可以看这个所有这个分支上的变量的梯度了。
若是最终计算标量的grad，不需要传入参数，但是最终结果若是向量，就得传入相同
维度的权重向量进行加权求和得到一个标量。
当一个函数的参数和结果都是向量的时候，这个y关于x的梯度就是一个雅克比矩阵。
需要使用torch.autograd这个包为雅克比矩阵进行求梯度。
grad在反向传播过程中是累加的，每一次运行反向传播，梯度总会累加之前，所以
一般反向传播之前将梯度清零,x.grad.data.zeros_()
#想要在计算图（tensor和function组成的一张计算图）中，仅仅是修改tensor的数值，
而不是影响到梯度计算（不被autgrad进行记录），可以使用x.data。
x.data是一个标量，但是不会对grad有影响，x的值虽然变了，但是梯度还是按照原来x的值进行计算
'''

import torch
torch.__version__

'1.3.1'

In [4]:
x = torch.rand(2,3,requires_grad = True)
print(x)
print(x.grad)

tensor([[0.4345, 0.1276, 0.3515],
        [0.4495, 0.7432, 0.8455]], requires_grad=True)
None


In [6]:
y=x+2
print(y)
print(y.grad_fn)

tensor([[2.4345, 2.1276, 2.3515],
        [2.4495, 2.7432, 2.8455]], grad_fn=<AddBackward0>)


In [7]:
print(x.is_leaf,y.is_leaf)

True False


In [8]:
z=y*y*3
out=z.mean()
print(z,out)

tensor([[17.7810, 13.5802, 16.5885],
        [17.9997, 22.5758, 24.2905]], grad_fn=<MulBackward0>) tensor(18.8026, grad_fn=<MeanBackward0>)


In [10]:
a = torch.randn(2,2)
a =((a*3)/(a-1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b=(a*a).sum()
print(b.grad_fn)

False
True


In [11]:
out.backward()

In [12]:
print(x.grad)

tensor([[2.4345, 2.1276, 2.3515],
        [2.4495, 2.7432, 2.8455]])


In [17]:
out_2 = x.sum()
out_2.backward()
print(x.grad)
out_3 = x.sum()
x.grad.data.zero_()
out_3.backward()
print(x.grad)

tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [19]:
x=torch.tensor([1.,2.,3.,4.],requires_grad=True)
y=2*x
z=y.view(2,2)
print(z)

tensor([[2., 4.],
        [6., 8.]], grad_fn=<ViewBackward>)


In [20]:
v=torch.tensor([[1.,0.1],[0.01,0.001]])
z.backward(v)
print(x.grad)

tensor([2.0000, 0.2000, 0.0200, 0.0020])


In [22]:
x = torch.tensor(1.0,requires_grad = True)
y1 = x**2
with torch.no_grad():
    y2=x**3
y3=y1+y2
print(x,x.requires_grad)
print(y1,y1.requires_grad)
print(y2,y2.requires_grad)
print(y3,y3.requires_grad)


tensor(1., requires_grad=True) True
tensor(1., grad_fn=<PowBackward0>) True
tensor(1.) False
tensor(2., grad_fn=<AddBackward0>) True


In [23]:
y3.backward()
print(x.grad)

tensor(2.)


In [24]:
x=torch.tensor(1.0,requires_grad=True)
print(x)
print(x.data)
print(x.data.requires_grad)

y=2*x
x.data*=100
y.backward()
print(x.grad)
print(x)


tensor(1., requires_grad=True)
tensor(1.)
False
tensor(2.)
tensor(100., requires_grad=True)
