In [1]:
!nvidia-smi

Sun Apr  5 20:22:18 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.64       Driver Version: 440.64       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce 940MX       Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   38C    P8    N/A /  N/A |    199MiB /  2004MiB |     10%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU  

In [3]:
import torch
from torch import nn
torch.cuda.is_available()

True

In [5]:
torch.cuda.device_count()

1

In [6]:
torch.cuda.current_device()

0

In [7]:
torch.cuda.get_device_name()

'GeForce 940MX'

In [8]:
x = torch.tensor([1,2,3])
x

tensor([1, 2, 3])

In [9]:
x = x.cuda(0)
x

tensor([1, 2, 3], device='cuda:0')

In [10]:
x.device

device(type='cuda', index=0)

In [11]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

x = torch.tensor([1,2,3],device=device)
x

tensor([1, 2, 3], device='cuda:0')

In [14]:
x = torch.tensor([1,2,3]).to(device)
y=x**2
y

tensor([1, 4, 9], device='cuda:0')

In [15]:
net=nn.Linear(3,1)
list(net.parameters())[0].device

device(type='cpu')

In [16]:
net.cuda()
list(net.parameters())[0].device

device(type='cuda', index=0)

In [18]:
x = torch.rand(2,3).cuda()
net(x)

tensor([[-0.4308],
        [-0.5244]], device='cuda:0', grad_fn=<AddmmBackward>)